services:
    zikula_categories_module.api.category_permission:
        class: Zikula\CategoriesModule\Api\CategoryPermissionApi
        arguments:
          - "@zikula_permissions_module.api.permission"
